# A Small Organization Jekyll Website Template
#
# This template is great for a small organization looking to save costs from hosting on wordpress
# or wix or squarespace make a simple DIY website for their organization and host it on github. This
# is the original open source template for modifying or you can fork this start changing to your website.
#
# This config file is meant for settings that affect your whole Site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Generic Non Profit
email: your-email@example.com
description: Generic Non Profit Website 
baseurl: /SmallOrganizationWebsite # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: org_twitter
github_username:  org_github



# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

  #Collections for Calendar
collections:
  events:
    output: true
    permalink: /events/:path/
    title: Events

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
